:warning: use spot instances
alphagov/verify-cluster-config pull request #122
Opened 2020-02-25 16:07 UTC by philandstuff

This sets `worker-on-demand-percentage-above-base` to 50.  This means
that, in each AZ, we run:

 - one guaranteed on-demand instance (the on-demand base capacity,
   which defaults to 1)
 - of the remaining instances, 50% of them will be on-demand and 50%
   will be spot instances.  The documentation doesn't actually specify
   how this is rounded - eg if there are 3 more instances, will there
   be 2 on-demand and 1 spot or 1 on-demand and 2 spot? :shrug:

2020-02-25 16:08 UTC, szd55gds approved these changes
Looks ok to me

2020-02-25 16:17 UTC, mrwilson approved these changes

2020-02-25 17:21 UTC, Krenair requested changes
Phil wanted to say 'DO NOT MERGE' but GitHub wouldn't let him during the GitHub problems

2021-04-27 12:26 UTC, Krenair commented
closing repo :(

2021-04-27 12:26 UTC, closed without merging